### ISSUE TITLE
file not recognized when install pycairo on manjaro

### ISSUE THREAD

**Issue by OriLiMu** [pygobject/pycairo#159]
manjaro 18.0.4

here is the log file you can search the keyword "failed" you can locate the error. 

I check this link https://bbs.archlinux.org/viewtopic.php?id=244367 but not work for me. 

The author mentioned about svgbob things but I have no idea what is the relationship with this case.  Almost zero solutions on web. 

[logfile.log](https://github.com/pygobject/pycairo/files/3882102/logfile.log)

I want to install the manim which a mathematical Animation Engine made by 3b1b. 
Thank you for your reply

**Comment by lazka** [comment]
Searching for this always leads to Arch and a broken binutils package. So I'd make sure your system is updated and you don't have things installed from AUR etc.

**Comment by woshichuanqilz** [comment]
> Searching for this always leads to Arch and a broken binutils package. So I'd make sure your system is updated and you don't have things installed from AUR etc.

Thanks a lot for your timely reply. 

The binutils package already installed the link I wrote in the first post have that. 
Both binutils and elfutils install and updated. 
pacman -Qi binutils 
> Name            : binutils
Version         : 2.33.1-1
Description     : A set of programs to assemble and manipulate binary and object files
Architecture    : x86_64
URL             : https://www.gnu.org/software/binutils/
Licenses        : GPL
Groups          : base-devel
Provides        : None
Depends On      : glibc  zlib
Optional Deps   : None
Required By     : appimagelauncher  gcc
Optional For    : None
Conflicts With  : binutils-multilib
Replaces        : binutils-multilib
Installed Size  : 29.25 MiB
Packager        : Bartłomiej Piotrowski <bpiotrowski@archlinux.org>
Build Date      : Mon 21 Oct 2019 02:07:39 PM CST
Install Date    : Sat 23 Nov 2019 06:13:56 PM CST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature


pacman -Qi elfutils 
> pacman  -Qi elfutils                                                                                   18:16:20
Name            : elfutils
Version         : 0.177-1
Description     : Utilities to handle ELF object files and DWARF debugging information
Architecture    : x86_64
URL             : https://sourceware.org/elfutils/
Licenses        : LGPL3  GPL  GPL3
Groups          : None
Provides        : None
Depends On      : libelf=0.177-1
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 1713.00 KiB
Packager        : Laurent Carlier <lordheavym@gmail.com>
Build Date      : Sun 01 Sep 2019 02:17:42 PM CST
Install Date    : Sat 23 Nov 2019 10:43:27 AM CST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

I ran command `sudo pacman -S binutils and elfutils` to install them.

**Comment by lazka** [comment]
No idea, sorry. Since this is your compiler toolchain failing I don't think there is anything I can do here.

**Comment by woshichuanqilz** [comment]
> No idea, sorry. Since this is your compiler toolchain failing I don't think there is anything I can do here.
> 
> (what's with all the anaconda paths in the logs? maybe you aren't even using the arch toolchain...)

solved by this link should downgrade the elfutils and libelf at the same time
https://bbs.archlinux.org/viewtopic.php?id=242682

But I get a new problem. 

I use the command `python -m pip --no-cache-dir  install -i https://pypi.tuna.tsinghua.edu.cn/simple pycairo==1.17.1 --user` with no cache option but still errors when I import pycairo

error is : 
>>> import cairo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lizhe/.local/lib/python3.7/site-packages/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
ImportError: /home/lizhe/.local/lib/python3.7/site-packages/cairo/_cairo.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cairo_tee_surface_index
Job 2, 'python' has stopped

Why this happened 

I already check this. But no-cache option not work for me.
