### ISSUE TITLE
Able to use pycairo 1.11.1 but not 1.20.0

### ISSUE THREAD

**Issue by TianyiShi2001** [pygobject/pycairo#223]
My system is Manjaro Linux 20.2, my Python version is 3.8.5, and I was experiencing the same problem as described in https://github.com/pygobject/pycairo/issues/148 , i.e., when trying to `import cairo`, I experience the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tianyi/anaconda3/lib/python3.8/site-packages/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
ImportError: /home/tianyi/anaconda3/lib/python3.8/site-packages/cairo/_cairo.cpython-38-x86_64-linux-gnu.so: undefined symbol: cairo_svg_surface_set_document_unit
```

I tried `pip3 install pycairo==1.11.1` and this solves the problem. Probably some changes in later versions made pycairo not back-compatible?

**Comment by rajatdash** [comment]
> My system is Manjaro Linux 20.2, my Python version is 3.8.5, and I was experiencing the same problem as described in #148 , i.e., when trying to `import cairo`, I experience the following error:
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/tianyi/anaconda3/lib/python3.8/site-packages/cairo/__init__.py", line 1, in <module>
>     from ._cairo import *  # noqa: F401,F403
> ImportError: /home/tianyi/anaconda3/lib/python3.8/site-packages/cairo/_cairo.cpython-38-x86_64-linux-gnu.so: undefined symbol: cairo_svg_surface_set_document_unit
> ```
> 
> I tried `pip3 install pycairo==1.11.1` and this solves the problem. Probably some changes in later versions made pycairo not back-compatible?

I had hard time using libcairo2-dev and pycairo in Ubuntu 18.04 LTS system. Tried all the options. But had "File "/usr/lib/python3/dist-packages/cairo/__init__.py", line 1, in <module>
    from ._cairo import *  # noqa: F401,F403
ModuleNotFoundError: No module named 'cairo._cairo'
" problem.
However I used 
$ python3.7 -m pip install pycairo==1.11.1
This has resolved the issue.Some issue is there in the current version of pycairo2-dev. Please look into it and resolve.
Thanks

**Comment by rajatdash** [comment]
Also I will give credit to https://www.reddit.com/r/Python/comments/doq8ye/installing_pycairo_issue/
