### ISSUE TITLE
utf8 decode error running snippets in python2

### ISSUE THREAD

**Issue by stuaxo** [pygobject/pycairo#35]
On Ubuntu 16.10 64 bit, in a venv

Seems like these files may ended up encoded in latin1, not utf8..
```
python snippets_svg.py 
Traceback (most recent call last):
  File "snippets_svg.py", line 48, in <module>
    snippets = get_snippets()
  File "/mnt/data/home/stu/projects/external/pycairo-projects/pycairo/pygobject-pycairo/examples/cairo_snippets/snippets/__init__.py", line 34, in get_snippets
    s.code = h.read().decode("utf-8")
  File "/mnt/data/home/stu/.virtualenvs/tmp-3a44fab5a6b060ee/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf3 in position 1: invalid continuation byte
```

**Comment by lazka** [comment]
weird, I can't reproduce.

**Comment by lazka** [comment]
It's because I have PYTHONDONTWRITEBYTECODE set globally and it tries to read the pyc files when they are there.
