### ISSUE TITLE
Cannot install pycairo 1.27 on ubuntu 22.04

### ISSUE THREAD

**Issue by nvincent-vossloh** [pygobject/pycairo#384]
Hello, on a fresh install (actually a docker image) of ubuntu 22.04, I cannot install pycairo with `pip install pycairo`:
```
pip install pycairo
Collecting pycairo
  Downloading pycairo-1.27.0.tar.gz (661 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 661.5/661.5 KB 4.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-a6gozn64/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 1020, in wrapper
          return func(*args, **kwargs)
        File "/tmp/pip-build-env-a6gozn64/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 1073, in build_wheel
          with _project(config_settings) as project:
        File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
          return next(self.gen)
        File "/tmp/pip-build-env-a6gozn64/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 947, in _project
          yield Project(source_dir, build_dir, meson_args, editable_verbose)
        File "/tmp/pip-build-env-a6gozn64/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 662, in __init__
          self._meson = _get_meson_command(pyproject_config.get('meson'))
        File "/tmp/pip-build-env-a6gozn64/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 982, in _get_meson_command
          meson_version = subprocess.run(cmd + ['--version'], check=False, text=True, capture_output=True).stdout
        File "/usr/lib/python3.10/subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'meson'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

If I install meson from the system package (0.61.2), then pycairo complains about meson being too old:

```
pip install pycairo
Collecting pycairo
  Using cached pycairo-1.27.0.tar.gz (661 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]

      meson-python: error: Could not find meson version 0.63.3 or newer, found 0.61.2
      meson-python: error: .
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

If I try to install `meson` through pip it goes farther, complains about cairo dependency not being installed which is solved by installing `libcairo2-dev`.

It looks like meson should be a dependency to pycairo, is it possible to modify pycairo package in order to install meson (if the version available on the system is too old) ?

For reference, here is the list of commands I executed:
Start a fresh ubuntu 22.04 container
```shell
docker run --rm -it -h SANDBOX ubuntu:22.04
```
From the container:
```shell
apt-get update
apt install -y pip
pip install pycairo
apt install -y meson
pip install pycairo
apt remove meson
pip install meson
pip install pycairo
apt install libcairo2-dev
pip install pycairo
```

Note: I tried installing an older version of pycairo, and it works with 1.26.1:
```shell
apt-get update
apt install -y pip
apt install -y libcairo2-dev
pip install pycairo==1.26.1
```

**Comment by lazka** [comment]
See https://github.com/mesonbuild/meson-python/issues/572. Please try with a newer pip.

**Comment by nvincent-vossloh** [comment]
Indeed adding 
```
pip install --upgrade pip
```
before trying to install pycairo worked.

Thanks for your help.
